version: "3"
services:
  # Container's name
  web:
    # Build from ./nginx/Dockerfile
    build:
      context: ./nginx
    # Port Mapping Host:Container
    ports:
      # range port mapping
      #- "8080-8100:80-100"
      - '80:80'
    # Keep nginx logs
    volumes:
      # mount configuration directory to container, you can edit conf at host machine directly.
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./www:/var/www/html/
      - ./logs/nginx:/var/log/nginx
    # Should restart auto
    restart: always
    # Should not up until services ready
    depends_on:
      - fpm
      - mysqldb

  # Container's for php-fpm
  fpm:
    # Build from ./fpm/Dockerfile
    build: 
      context: ./fpm
    # mount folder to container
    volumes:
      # Web application directory
      - ./www:/var/www/html:rw
      # Keep php logs
      - ./logs/php:/var/log/php
      # Mount script/toolkit for container
      - ./fpm/scripts:/var/www/bin
    # Setup the environment variables
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # Should restart auto
    restart: always

  # Container's for php-compose
  composer:
    # Just get the latest version of composer
    image: composer
    # mount the web folder
    volumes:
      - ./www:/var/www/html
    # Point this to your app directory
    # working_dir: /var/www/html/myapp
    # This need to be modify
    # command: install -vvv

  # Container's for mysql
  mysqldb:
    # Build from ./sql/Dockerfile
    build:
      context: ./sql
    # Rename the container
    container_name: ${MYSQL_HOST}
    # Setup the env - This will store at volume once it have been created
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # Port Mapping Host:Container
    ports:
      - "3306:3306"
    # use data-volume to keep the mysql data
    volumes:
      - data-volume:/var/lib/mysql
    restart: always

# MySQL store at docker volume
volumes:
  data-volume: